### ISSUE TITLE
Nav content overflow

### ISSUE THREAD

**Issue by Novsun30** [Pinkowo/cheese-elephant#1]
I found that Nav content overflow in firefox, but is normal in chrome and edge
I'm not sure this only happend on my PC or something

### **[ Overflow in FireFox ]**
![image](https://user-images.githubusercontent.com/107986642/210327070-abb9c2da-18ab-40cd-8004-740a9a4ef9b1.png)

**Comment by Pinkowo** [comment]
oh no...thx for let me know
Have u tried pressing F5? Sometimes it's bc of cache
If it still happens, I'll figure out or just let it go lol

**Comment by Novsun30** [comment]
Tried F5, nothing changed ~
Does this show normally on your Firefox?
If its normal, maybe just my own problem and you can ignore me 😃

**Comment by Pinkowo** [comment]
Actually I don't have Firefox (´∀｀；)
Let me download it and answer you later～

**Comment by Pinkowo** [comment]
Okay I found the problem. 
In base.css, you can delete `width: 356px;` of .header-nav. It won't change anything but fix the bug.
The final version will be correct.
Thank you for pointing out this bug~
